version: 2
sphinx:
  builder: html
  configuration: doc/manual/source/conf.py
formats: all
python:
  version: 3.7
  install:
    - requirements: doc/manual/requirements.txt
submodules:
  exclude: all
